### PR TITLE
Create MANIFEST.in

### PR DESCRIPTION
**Pull request by knil-sama**
Add MANIFEST.in so installation from remote git include s4cmd command file from data/bash-completion/s4cmd.

See https://github.com/bloomreach/s4cmd/issues/73

### CODE REVIEW

**Comment by rturam** [comment]
Where to add this file?

**Comment by knil-sama** [comment]
@rturam at the root of the project where the setup.py is located

**Comment by rturam** [comment]
Thanks.
I am not able to setup it anyway.
I have RHEL 6 and python 2.6 , so when I installed through 
`pip install s4cmd`
and then run s4cmd command i get below error:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/src/s4cmd/s4cmd.py", line 41, in <module>
    from functools import cmp_to_key
ImportError: cannot import name cmp_to_key
```

**Comment by knil-sama** [comment]
Yea it didn't work with python 2.6, see this issue on the official repository #https://github.com/bloomreach/s4cmd/pull/36

**Comment by rturam** [comment]
Hence I installed(with source compiling) Python 2.7 without disturbing 2.6 version, still getting the error which is mentioned for this issue bloomreach#73. 
Actually, it downloads the package in /tmp dir and from there it copies to python2.7/site-package and tries to install. I have added the MANIFEST.in as mentioned but still no change in error.

**Comment by knil-sama** [comment]
@rturam so you did un git clone of the official repo, put my manifest inside, then run `python2.7 setup.py install `?

**Comment by rturam** [comment]
Hi, now I was able to install properly. Some how it was using python 2.6 and that's why it was failing. Thanks a lot!
